### ISSUE TITLE
Not an issue, just wanted to get in touch..

### ISSUE THREAD

**Issue by futurepr0n** [sungwoncho/node-ufc-api#2]
Hi Sung - I'm a hobbyist developer that's a big MMA fan and was working towards a project I was wondering whether another MMA fan and developer such as yourself might be interested in collaboration?

I started building my own scraper before stumbling upon your reddit post and saw you  also pursuing something similar. As a fellow mma fan and developer just thought I'd reach out to gauge whether you would be into the idea of working on something together.

Im basically looking to develop a pretty ambitious, but what I believe is super achieveable, mma portal.

I have a great domain, and some of the scraper developed but I'd love to get some other interested people involved because although I'm motivated on my own, progress is achieved much faster through teamwork.

Anyways! Please reach back out to me if you'd like to have a conversation about it.

**Comment by sungwoncho** [comment]
Hey. I'd love to collaborate given that your project is open source and noncommercial. If so we can talk more on twitter: @mikeswcho. Cheers.
