### ISSUE TITLE
Returning HTML instead of JSON

### ISSUE THREAD

**Issue by vash88** [sungwoncho/node-ufc-api#3]
`fighter(id, callback)` & `event(id, callback)` results return HTML instead of JSON.

For example:
http://ufc-data-api.ufc.com/api/v3/us/fighters/500
http://ufc-data-api.ufc.com/api/v3/us/fighters/500.json

**Comment by sungwoncho** [comment]
I think we need to append `.json` for those routes. Could you make a PR and ping me?

**Comment by sungwoncho** [comment]
See here: https://github.com/sungwoncho/node-ufc-api/blob/master/lib/v3/api.js#L59
